drop schema if exists charp;
create schema CHARP;
USE CHARP;
CREATE TABLE USERS (
    ID INT AUTO_INCREMENT,
    PRIMARY KEY (ID),
    USERNAME VARCHAR(45) UNIQUE,
    PASSWORD VARCHAR(45) NOT NULL
);
CREATE TABLE LEADERBOARDS (
    ID INT AUTO_INCREMENT,
    USERNAME VARCHAR(45) NOT NULL,
    SIZE VARCHAR(30) NOT NULL,
    TIME INT NOT NULL,
    COUNT INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (USERNAME)
        REFERENCES USERS (USERNAME)
);
CREATE TABLE GAMES (
    ID INT AUTO_INCREMENT,
    USERNAME VARCHAR(45) NOT NULL,
    STATE VARCHAR(8000) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (USERNAME)
        REFERENCES USERS (USERNAME)
);
CREATE INDEX USERNAME_INDEX ON USERS(USERNAME);
CREATE INDEX USERNAME_INDEX ON GAMES(USERNAME);
CREATE INDEX USERNAME_INDEX ON LEADERBOARDS(USERNAME);